language: node_js
cache: yarn
node_js:
- stable
- '6'
- '4'
deploy:
  provider: npm
  api_key: $NPM_API_KEY
  on: deploy-npm-release
  email: wal.mokrani@gmail.com
env:
  global:
    $NPM_API_KEY: J9Wv5XBdfqDVVPGvd73qDRYXFMpbWHFUpGd944H+cveH6dDykQQtruzCkLCDjJZwfgRWpVnB+vyWOE8UDoui64EJN2fdeamlYHTesEnI5Q1bBHBQxmG+HQWmSgmUDvPNA6igO5Tmu3xpYyndYkhx7y7mmuLdRvg1wk8CTonHZYXJGlESlUwcGp5ACq6d/NXIU/AG4oN9Wu8MfY9rzmziIJ0iiSb7Ty86gIymxBsM9BK5Or7CWKGWqiNRjihQDvIWbO8v2tokZlGMgpCU+8vevR+BxCeAYxYlZZcdmy/DXmPaAYElgmz5UlvGsrDEAfmXNcpSRTyNMcCHTbU5M3lJyaqUryoZPTDsORBxjNJelBDMFzfSFO6unv4tsovbYbltysY63bXIQsF2Sk5NLB/3/jfBUmKWOd6dVsc1U/p0Hrkvc9eqMSHCam6FGtmNBTYfn/5nbCJVSpKgpP/5N2kyp9wUCb+D5rKs6cAjYNKABGjMkriFt5EPwng+Y5+xGumLX3qrfYyNpL9Pp7n0f4L3cclszaO+qZzbQWIPnhXxEO1T9abLeg9b1MP5MJ+hiJA3GhNF+y+g2YMe5YD9rVdzqh0HasPEDVLzqlz91hPeny8pCYi+v5cnIrkUh+QHVEeOgysMyXPPvA32Kea45vyhE8cFgI3hH9vIor9POz6qDB0=